version: '3.9'

services:
  simple-wms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-python
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
